package gecko.test

internal class TestSuccessful : RuntimeException()